prepare release 20240314
phoenix-rtos/phoenix-rtos-docker pull request #32
Opened 2024-03-14 15:05 UTC by mateusz-bloch

2024-03-18 23:03 UTC, damianloew submitted a review, later dismissed
LGTM. Please remember about pushing a proper tag after merge (like it was done earlier). You can also consider pushing the images to ghcr - it's not crucial, but I think it's good to have them up to date

2024-03-18 23:33 UTC, nalajcie requested changes
- `build` image was not rebuilt (and not re-tagged/re-uploaded to the dockerhub) - **please follow the release instruction to the letter!**
 - as the `build` image wasn't rebuilt, the p-r-p commit is not true (it's different for `build` and `devel` images - please specify the corresponding commit hashes (examples below) and/or rebuild / push build` image also)

2024-03-19 14:05 UTC, damianloew commented
> * `build` image was not rebuilt (and not re-tagged/re-uploaded to the dockerhub) - **please follow the release instruction to the letter!**
> * as the `build` image wasn't rebuilt, the p-r-p commit is not true (it's different for `build` and `devel` images - please specify the corresponding commit hashes (examples below) and/or rebuild / push build` image also)

Sorry that we missed that, the build image will be pushed with the same tag. Also devel and build hashes will be specified separately.

2024-03-19 15:24 UTC, nalajcie approved these changes

2024-03-19 19:49 UTC, merged